# .github/workflows/build.yml

name: build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Building...'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: panelatta/panelatta.github.io
        DEPLOY_BRANCH: gh-pages
        DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        TZ: Asia/Shanghai

